AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions OIDC with minimal permissions for SST deployment'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization or username
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  OIDCProviderArn:
    Type: String
    Description: ARN of the GitHub OIDC Provider (if already exists, otherwise leave empty)
    Default: ''

Conditions:
  CreateOIDCProvider: !Equals [!Ref OIDCProviderArn, '']

Resources:
  # GitHub OIDC Provider (only if not exists)
  GithubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

  # IAM Role for GitHub Actions
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${GitHubRepo}-github-actions-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !GetAtt GithubOIDCProvider.Arn
                - !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub':
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/tags/v*'
      ManagedPolicyArns:
        - !Ref SSTDeploymentPolicy
      Tags:
        - Key: Purpose
          Value: GitHub Actions OIDC

  # Custom policy for SST deployment (minimal permissions)
  SSTDeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${GitHubRepo}-sst-deployment-policy'
      Description: 'Minimal permissions for SST deployment to AWS'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # CloudFormation permissions
          - Sid: CloudFormationAccess
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:GetTemplate
              - cloudformation:ValidateTemplate
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:ListStacks
            Resource: '*'

          # S3 permissions for assets and static sites
          - Sid: S3Access
            Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetBucketPolicy
              - s3:PutBucketPolicy
              - s3:DeleteBucketPolicy
              - s3:PutBucketWebsite
              - s3:PutBucketVersioning
              - s3:PutBucketCORS
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:PutBucketPublicAccessBlock
              - s3:PutLifecycleConfiguration
            Resource:
              - !Sub 'arn:aws:s3:::${GitHubRepo}-*'
              - !Sub 'arn:aws:s3:::${GitHubRepo}-*/*'

          # CloudFront permissions
          - Sid: CloudFrontAccess
            Effect: Allow
            Action:
              - cloudfront:CreateDistribution
              - cloudfront:UpdateDistribution
              - cloudfront:DeleteDistribution
              - cloudfront:GetDistribution
              - cloudfront:GetDistributionConfig
              - cloudfront:ListDistributions
              - cloudfront:TagResource
              - cloudfront:UntagResource
              - cloudfront:CreateInvalidation
              - cloudfront:GetInvalidation
              - cloudfront:CreateOriginAccessControl
              - cloudfront:GetOriginAccessControl
              - cloudfront:UpdateOriginAccessControl
              - cloudfront:DeleteOriginAccessControl
            Resource: '*'

          # Lambda permissions for SSR
          - Sid: LambdaAccess
            Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:UpdateFunctionCode
              - lambda:UpdateFunctionConfiguration
              - lambda:DeleteFunction
              - lambda:GetFunction
              - lambda:GetFunctionConfiguration
              - lambda:PublishVersion
              - lambda:ListVersionsByFunction
              - lambda:CreateAlias
              - lambda:UpdateAlias
              - lambda:DeleteAlias
              - lambda:GetAlias
              - lambda:InvokeFunction
              - lambda:AddPermission
              - lambda:RemovePermission
              - lambda:TagResource
              - lambda:UntagResource
            Resource: !Sub 'arn:aws:lambda:*:${AWS::AccountId}:function:${GitHubRepo}-*'

          # IAM permissions for Lambda execution roles
          - Sid: IAMRoleAccess
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetRole
              - iam:PassRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:GetRolePolicy
              - iam:TagRole
              - iam:UntagRole
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${GitHubRepo}-*'

          # SSM Parameter Store for SST state
          - Sid: SSMParameterAccess
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:PutParameter
              - ssm:DeleteParameter
              - ssm:AddTagsToResource
              - ssm:RemoveTagsFromResource
            Resource:
              - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/sst/${GitHubRepo}/*'
              - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/sst/bootstrap'

          # Additional permissions for SST
          - Sid: AdditionalSST
            Effect: Allow
            Action:
              - sts:GetCallerIdentity
              - route53:ListHostedZones
              - route53:GetHostedZone
              - route53:ChangeResourceRecordSets
              - route53:GetChange
              - acm:ListCertificates
              - acm:DescribeCertificate
              - acm:RequestCertificate
              - acm:DeleteCertificate
              - acm:AddTagsToCertificate
            Resource: '*'

Outputs:
  RoleArn:
    Description: ARN of the IAM Role for GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  RoleName:
    Description: Name of the IAM Role
    Value: !Ref GitHubActionsRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
